// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_cluster

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func ClusterResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description:         "Manages a RunPod Instant Cluster via the GraphQL API. Clusters have no REST v2 surface.",
		MarkdownDescription: "Manages a RunPod Instant Cluster via the GraphQL API. Clusters have no REST v2 surface; all attributes force replacement — the backend has no in-place cluster update.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Cluster ID",
				MarkdownDescription: "Cluster ID",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cluster name (auto-generated when omitted)",
				MarkdownDescription: "Cluster name (auto-generated when omitted)",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "Cluster type, e.g. SLURM, TRAINING, APPLICATION, RAY (passed through unvalidated; availability depends on backend deploy state and feature gates)",
				MarkdownDescription: "Cluster type, e.g. `SLURM`, `TRAINING`, `APPLICATION`, `RAY`. Passed through unvalidated — new types work without a provider release. `RAY` additionally requires the backend flag to be enabled for the caller.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"gpu_type_id": schema.StringAttribute{
				Required:            true,
				Description:         "GPU type ID, e.g. \"NVIDIA H100 80GB HBM3\"",
				MarkdownDescription: "GPU type ID, e.g. `\"NVIDIA H100 80GB HBM3\"`. Cluster-capable capacity is listed per GPU type under nodeGroupDatacenters in the GraphQL gpuTypes query.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"pod_count": schema.Int64Attribute{
				Required:            true,
				Description:         "Number of pods in the cluster",
				MarkdownDescription: "Number of pods in the cluster. Private pools allocate whole nodes — set gpu_count_per_pod to the node's full GPU count.",
				PlanModifiers:       []planmodifier.Int64{int64planmodifier.RequiresReplace()},
			},
			"gpu_count_per_pod": schema.Int64Attribute{
				Required:            true,
				Description:         "GPUs per pod",
				MarkdownDescription: "GPUs per pod",
				PlanModifiers:       []planmodifier.Int64{int64planmodifier.RequiresReplace()},
			},
			"deploy_cost": schema.Float64Attribute{
				Optional:            true,
				Description:         "Max price basis for deployment",
				MarkdownDescription: "Max price basis for deployment. Validated per-GPU-unit against the minimum bid (i.e. must be >= per-GPU min x pod_count x gpu_count_per_pod).",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.RequiresReplace()},
			},
			"data_center_ids": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Restrict placement to these data centers",
				MarkdownDescription: "Restrict placement to these data centers, e.g. the DC backing a private pool.",
				PlanModifiers:       []planmodifier.List{listplanmodifier.RequiresReplace()},
			},
			"template_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Template ID to base cluster pods on",
				MarkdownDescription: "Template ID to base cluster pods on",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"image_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Container image name",
				MarkdownDescription: "Container image name",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"container_disk_in_gb": schema.Int64Attribute{
				Optional:            true,
				Description:         "Container disk size in GB",
				MarkdownDescription: "Container disk size in GB",
				PlanModifiers:       []planmodifier.Int64{int64planmodifier.RequiresReplace()},
			},
			"ports": schema.StringAttribute{
				Optional:            true,
				Description:         "Ports string, e.g. \"8888/http,22/tcp\"",
				MarkdownDescription: "Ports string, e.g. `\"8888/http,22/tcp\"`",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"network_volume_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Network volume to mount",
				MarkdownDescription: "Network volume to mount",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"env": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Environment variables for cluster pods",
				MarkdownDescription: "Environment variables for cluster pods",
				PlanModifiers:       []planmodifier.Map{mapplanmodifier.RequiresReplace()},
			},
			"pods": schema.ListNestedAttribute{
				Computed:            true,
				Description:         "Cluster pods as reported by the API on read",
				MarkdownDescription: "Cluster pods as reported by the API on read. Populated on refresh, not at apply time — pods take minutes to reach RUNNING.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "Pod ID",
							MarkdownDescription: "Pod ID",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Pod name",
							MarkdownDescription: "Pod name",
						},
						"cluster_idx": schema.Int64Attribute{
							Computed:            true,
							Description:         "Pod index within the cluster (0-based; index 0 runs the head/controller role)",
							MarkdownDescription: "Pod index within the cluster (0-based; index 0 runs the head/controller role)",
						},
						"cluster_role": schema.StringAttribute{
							Computed:            true,
							Description:         "Cluster role, e.g. SLURM_CONTROLLER / SLURM_COMPUTE / RAY_HEAD / RAY_WORKER",
							MarkdownDescription: "Cluster role, e.g. `SLURM_CONTROLLER` / `SLURM_COMPUTE` / `RAY_HEAD` / `RAY_WORKER`",
						},
						"cluster_ip": schema.StringAttribute{
							Computed:            true,
							Description:         "Interconnect IP inside the cluster network",
							MarkdownDescription: "Interconnect IP inside the cluster network",
						},
						"desired_status": schema.StringAttribute{
							Computed:            true,
							Description:         "Pod lifecycle status, e.g. RUNNING / EXITED",
							MarkdownDescription: "Pod lifecycle status, e.g. `RUNNING` / `EXITED`",
						},
					},
				},
			},
		},
	}
}

type ClusterModel struct {
	Id                types.String      `tfsdk:"id"`
	Name              types.String      `tfsdk:"name"`
	Type              types.String      `tfsdk:"type"`
	GpuTypeId         types.String      `tfsdk:"gpu_type_id"`
	PodCount          types.Int64       `tfsdk:"pod_count"`
	GpuCountPerPod    types.Int64       `tfsdk:"gpu_count_per_pod"`
	DeployCost        types.Float64     `tfsdk:"deploy_cost"`
	DataCenterIds     types.List        `tfsdk:"data_center_ids"`
	TemplateId        types.String      `tfsdk:"template_id"`
	ImageName         types.String      `tfsdk:"image_name"`
	ContainerDiskInGb types.Int64       `tfsdk:"container_disk_in_gb"`
	Ports             types.String      `tfsdk:"ports"`
	NetworkVolumeId   types.String      `tfsdk:"network_volume_id"`
	Env               types.Map         `tfsdk:"env"`
	Pods              []ClusterPodModel `tfsdk:"pods"`
}

type ClusterPodModel struct {
	Id            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	ClusterIdx    types.Int64  `tfsdk:"cluster_idx"`
	ClusterRole   types.String `tfsdk:"cluster_role"`
	ClusterIp     types.String `tfsdk:"cluster_ip"`
	DesiredStatus types.String `tfsdk:"desired_status"`
}
