// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_pod_action

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PodActionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"action": schema.StringAttribute{
				Required:            true,
				Description:         "Action to perform: start, stop, restart, terminate",
				MarkdownDescription: "Action to perform: start, stop, restart, terminate",
			},
			"pod_id": schema.StringAttribute{
				Required:            true,
				Description:         "The pod ID to act on",
				MarkdownDescription: "The pod ID to act on",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Status after action",
				MarkdownDescription: "Status after action",
			},
		},
	}
}

type PodActionModel struct {
	Action types.String `tfsdk:"action"`
	PodId  types.String `tfsdk:"pod_id"`
	Status types.String `tfsdk:"status"`
}
