// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_ecr_delegation

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func EcrDelegationResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "ECR delegation identifier",
				MarkdownDescription: "ECR delegation identifier",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Optional name for the delegation",
				MarkdownDescription: "Optional name for the delegation",
			},
			"resource": schema.StringAttribute{
				Required:            true,
				Description:         "ECR resource ARN (e.g., arn:aws:ecr:us-east-2:123456789:repository/myapp)",
				MarkdownDescription: "ECR resource ARN (e.g., `arn:aws:ecr:us-east-2:123456789:repository/myapp`)",
			},
			"aws_user": schema.StringAttribute{
				Computed:            true,
				Description:         "AWS user/role being delegated",
				MarkdownDescription: "AWS user/role being delegated",
			},
			"repository": schema.StringAttribute{
				Computed:            true,
				Description:         "ECR repository name",
				MarkdownDescription: "ECR repository name",
			},
			"tag": schema.StringAttribute{
				Computed:            true,
				Description:         "ECR image tag",
				MarkdownDescription: "ECR image tag",
			},
			"aws_region": schema.StringAttribute{
				Computed:            true,
				Description:         "AWS region",
				MarkdownDescription: "AWS region",
			},
			"docker_registry_uri": schema.StringAttribute{
				Computed:            true,
				Description:         "Formatted ECR registry URI for Docker login",
				MarkdownDescription: "Formatted ECR registry URI for Docker login",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "When the delegation was created",
				MarkdownDescription: "When the delegation was created",
			},
		},
	}
}

type EcrDelegationModel struct {
	Id                  types.String `tfsdk:"id"`
	Name                types.String `tfsdk:"name"`
	Resource            types.String `tfsdk:"resource"`
	AwsUser             types.String `tfsdk:"aws_user"`
	Repository          types.String `tfsdk:"repository"`
	Tag                 types.String `tfsdk:"tag"`
	AwsRegion           types.String `tfsdk:"aws_region"`
	DockerRegistryUri   types.String `tfsdk:"docker_registry_uri"`
	CreatedAt           types.String `tfsdk:"created_at"`
}
