// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_endpoint

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/attr"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func EndpointResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allowed_cuda_versions": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "List of allowed CUDA versions",
				MarkdownDescription: "List of allowed CUDA versions",
			},
			"compute_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Compute type: GPU or CPU",
				MarkdownDescription: "Compute type: GPU or CPU",
			},
			"cpu_flavor_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "List of CPU flavor IDs",
				MarkdownDescription: "List of CPU flavor IDs",
			},
			"cpu_flavor_priority": schema.StringAttribute{
				Optional:            true,
				Description:         "CPU flavor priority: availability or custom",
				MarkdownDescription: "CPU flavor priority: availability or custom",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Creation timestamp",
				MarkdownDescription: "Creation timestamp",
			},
			"data_center_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "List of data center IDs",
				MarkdownDescription: "List of data center IDs",
			},
			"env": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Environment variables",
				MarkdownDescription: "Environment variables",
			},
			"execution_timeout_ms": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Execution timeout in milliseconds",
				MarkdownDescription: "Execution timeout in milliseconds",
			},
			"flashboot": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable flashboot",
				MarkdownDescription: "Enable flashboot",
			},
			"gpu_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of GPUs",
				MarkdownDescription: "Number of GPUs",
			},
			"gpu_type_id": schema.StringAttribute{
				Optional:    true,
				Description: "GPU type ID (v2 required)",
				MarkdownDescription: "GPU type ID. Required when creating endpoint with v2 API.",
			},
			"gpu_type_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "List of GPU type IDs",
				MarkdownDescription: "List of GPU type IDs",
			},
			"gpu_type_priority": schema.StringAttribute{
				Optional:            true,
				Description:         "GPU type priority: availability or custom",
				MarkdownDescription: "GPU type priority: availability or custom",
			},
			"cloud_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cloud type: COMMUNITY or SECURE",
				MarkdownDescription: "Cloud type: COMMUNITY or SECURE",
			},
			"container_disk_in_gb": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Container disk size in GB",
				MarkdownDescription: "Container disk size in GB",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Endpoint ID",
				MarkdownDescription: "Endpoint ID",
			},
			"idle_timeout": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Idle timeout in minutes",
				MarkdownDescription: "Idle timeout in minutes",
			},
			"min_cuda_version": schema.StringAttribute{
				Optional:            true,
				Description:         "Minimum CUDA version required",
				MarkdownDescription: "Minimum CUDA version required",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Description:         "Endpoint name",
				MarkdownDescription: "Endpoint name",
			},
			"network_volume_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Network volume ID",
				MarkdownDescription: "Network volume ID",
			},
			"network_volume_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "List of network volume IDs",
				MarkdownDescription: "List of network volume IDs",
			},
			"scaler_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Scaler type: QUEUE_DELAY or REQUEST_COUNT",
				MarkdownDescription: "Scaler type: QUEUE_DELAY or REQUEST_COUNT",
			},
			"scaler_value": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Scaler value",
				MarkdownDescription: "Scaler value",
			},
			"image_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Container image name (v2 required)",
				MarkdownDescription: "Container image name (v2 required). Required when creating endpoint with v2 API.",
			},
			"template_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Template ID for the endpoint (deprecated in v2)",
				MarkdownDescription: "Template ID for the endpoint. Deprecated in v2 - use image_name instead.",
			},
			"template_version": schema.Int64Attribute{
				Computed:            true,
				Description:         "Template version",
				MarkdownDescription: "Template version",
			},
			"users": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
				Description: "List of user IDs with access",
				MarkdownDescription: "List of user IDs with access",
			},
			"version": schema.Int64Attribute{
				Computed:            true,
				Description:         "Endpoint version",
				MarkdownDescription: "Endpoint version",
			},
			"vcpu_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of vCPUs",
				MarkdownDescription: "Number of vCPUs",
			},
			"workers": schema.ListAttribute{
				ElementType: types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"id":           types.StringType,
						"pod_id":       types.StringType,
						"status":       types.StringType,
						"uptime_ms":    types.Int64Type,
						"start_time":   types.StringType,
						"last_busy_ms": types.Int64Type,
					},
				},
				Computed:    true,
				Description: "List of workers (pods)",
				MarkdownDescription: "List of workers (pods)",
			},
			"workers_max": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Maximum number of workers",
				MarkdownDescription: "Maximum number of workers",
			},
			"workers_min": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Minimum number of workers",
				MarkdownDescription: "Minimum number of workers",
			},
		},
	}
}

type EndpointModel struct {
	AllowedCudaVersions  types.List   `tfsdk:"allowed_cuda_versions"`
	ComputeType          types.String `tfsdk:"compute_type"`
	CpuFlavorIds         types.List   `tfsdk:"cpu_flavor_ids"`
	CpuFlavorPriority    types.String `tfsdk:"cpu_flavor_priority"`
	CreatedAt            types.String `tfsdk:"created_at"`
	DataCenterIds        types.List   `tfsdk:"data_center_ids"`
	Env                  types.Map    `tfsdk:"env"`
	ExecutionTimeoutMs   types.Int64  `tfsdk:"execution_timeout_ms"`
	Flashboot            types.Bool   `tfsdk:"flashboot"`
	GpuCount             types.Int64  `tfsdk:"gpu_count"`
	GpuTypeId            types.String `tfsdk:"gpu_type_id"`
	GpuTypeIds           types.List   `tfsdk:"gpu_type_ids"`
	GpuTypePriority      types.String `tfsdk:"gpu_type_priority"`
	CloudType            types.String `tfsdk:"cloud_type"`
	ContainerDiskInGb    types.Int64  `tfsdk:"container_disk_in_gb"`
	ImageName            types.String `tfsdk:"image_name"`
	Id                   types.String `tfsdk:"id"`
	IdleTimeout          types.Int64  `tfsdk:"idle_timeout"`
	MinCudaVersion       types.String `tfsdk:"min_cuda_version"`
	Name                 types.String `tfsdk:"name"`
	NetworkVolumeId      types.String `tfsdk:"network_volume_id"`
	NetworkVolumeIds     types.List   `tfsdk:"network_volume_ids"`
	ScalerType           types.String `tfsdk:"scaler_type"`
	ScalerValue          types.Int64  `tfsdk:"scaler_value"`
	TemplateId           types.String `tfsdk:"template_id"`
	TemplateVersion      types.Int64  `tfsdk:"template_version"`
	Users                types.List   `tfsdk:"users"`
	Version              types.Int64  `tfsdk:"version"`
	VcpuCount            types.Int64  `tfsdk:"vcpu_count"`
	Workers              types.List   `tfsdk:"workers"`
	WorkersMax           types.Int64  `tfsdk:"workers_max"`
	WorkersMin           types.Int64  `tfsdk:"workers_min"`
}
