// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_container_registry_auth

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ContainerRegistryAuthResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Container registry auth ID",
				MarkdownDescription: "Container registry auth ID",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Container registry auth name (must be unique)",
				MarkdownDescription: "Container registry auth name (must be unique)",
			},
			"password": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "Container registry password",
				MarkdownDescription: "Container registry password",
			},
			"username": schema.StringAttribute{
				Required:            true,
				Description:         "Container registry username",
				MarkdownDescription: "Container registry username",
			},
		},
	}
}

type ContainerRegistryAuthModel struct {
	Id       types.String `tfsdk:"id"`
	Name     types.String `tfsdk:"name"`
	Password types.String `tfsdk:"password"`
	Username types.String `tfsdk:"username"`
}
