// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_user

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "User ID",
				MarkdownDescription: "User ID",
			},
			"pub_key": schema.StringAttribute{
				Computed:            true,
				Description:         "User's public SSH key",
				MarkdownDescription: "User's public SSH key",
			},
		},
	}
}

type UserModel struct {
	Id     types.String `tfsdk:"id"`
	PubKey types.String `tfsdk:"pub_key"`
}
