// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_template

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func TemplateDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Template ID to look up",
				MarkdownDescription: "Template ID to look up",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Template name",
				MarkdownDescription: "Template name",
			},
			"image_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Docker image name",
				MarkdownDescription: "Docker image name",
			},
			"category": schema.StringAttribute{
				Computed:            true,
				Description:         "Category: NVIDIA, AMD, or CPU",
				MarkdownDescription: "Category: NVIDIA, AMD, or CPU",
			},
			"container_disk_in_gb": schema.Int64Attribute{
				Computed:            true,
				Description:         "Container disk size in GB",
				MarkdownDescription: "Container disk size in GB",
			},
			"container_registry_auth_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Container registry authentication ID",
				MarkdownDescription: "Container registry authentication ID",
			},
			"docker_entrypoint": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Docker entrypoint array",
				MarkdownDescription: "Docker entrypoint array",
			},
			"docker_start_cmd": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Docker start command array",
				MarkdownDescription: "Docker start command array",
			},
			"env": schema.ObjectAttribute{
				Computed:            true,
				Description:         "Environment variables object",
				MarkdownDescription: "Environment variables object",
			},
			"is_public": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether template is public",
				MarkdownDescription: "Whether template is public",
			},
			"is_serverless": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether template is serverless",
				MarkdownDescription: "Whether template is serverless",
			},
			"ports": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Ports array",
				MarkdownDescription: "Ports array",
			},
			"readme": schema.StringAttribute{
				Computed:            true,
				Description:         "Template readme/documentation",
				MarkdownDescription: "Template readme/documentation",
			},
			"volume_in_gb": schema.Int64Attribute{
				Computed:            true,
				Description:         "Volume size in GB",
				MarkdownDescription: "Volume size in GB",
			},
			"volume_mount_path": schema.StringAttribute{
				Computed:            true,
				Description:         "Volume mount path",
				MarkdownDescription: "Volume mount path",
			},
			"earned": schema.Float64Attribute{
				Computed:            true,
				Description:         "Credits earned by template usage",
				MarkdownDescription: "Credits earned by template usage",
			},
			"is_runpod": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether it's an official RunPod template",
				MarkdownDescription: "Whether it's an official RunPod template",
			},
			"runtime_in_min": schema.Int64Attribute{
				Computed:            true,
				Description:         "Runtime in minutes",
				MarkdownDescription: "Runtime in minutes",
			},
		},
	}
}

type TemplateModel struct {
	Id                      types.String  `tfsdk:"id"`
	Name                    types.String  `tfsdk:"name"`
	ImageName               types.String  `tfsdk:"image_name"`
	Category                types.String  `tfsdk:"category"`
	ContainerDiskInGb       types.Int64   `tfsdk:"container_disk_in_gb`
	ContainerRegistryAuthId types.String  `tfsdk:"container_registry_auth_id`
	DockerEntrypoint        types.List    `tfsdk:"docker_entrypoint`
	DockerStartCmd          types.List    `tfsdk:"docker_start_cmd`
	Env                     types.Object  `tfsdk:"env"`
	IsPublic                types.Bool    `tfsdk:"is_public`
	IsServerless            types.Bool    `tfsdk:"is_serverless`
	Ports                   types.List    `tfsdk:"ports`
	Readme                  types.String  `tfsdk:"readme`
	VolumeInGb              types.Int64   `tfsdk:"volume_in_gb`
	VolumeMountPath         types.String  `tfsdk:"volume_mount_path`
	Earned                  types.Float64 `tfsdk:"earned`
	IsRunpod                types.Bool    `tfsdk:"is_runpod`
	RuntimeInMin            types.Int64   `tfsdk:"runtime_in_min`
}
