// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_pod

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PodResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bid_per_gpu": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Bid price per GPU for interruptible pods - DEPRECATED: Use scheduling.bidPerGpu",
				MarkdownDescription: "Bid price per GPU for interruptible pods - DEPRECATED: Use scheduling.bidPerGpu instead.",
			},
			"type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Pod type: ON_DEMAND or SPOT (v2 required field)",
				MarkdownDescription: "Pod type: ON_DEMAND or SPOT (v2 required field). Set to SPOT for interruptible pods.",
			},
			"cloud_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cloud type: COMMUNITY, SECURE, or ALL - DEPRECATED: Use scheduling.cloudType",
				MarkdownDescription: "Cloud type: COMMUNITY, SECURE, or ALL - DEPRECATED: Use scheduling.cloudType instead.",
			},
			"cluster_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "Cluster IP address",
				MarkdownDescription: "Cluster IP address",
			},
			"container_disk_in_gb": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Container disk size in GB",
				MarkdownDescription: "Container disk size in GB",
			},
			"cost_per_hr": schema.Float64Attribute{
				Computed:            true,
				Description:         "Cost per hour",
				MarkdownDescription: "Cost per hour",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Creation timestamp",
				MarkdownDescription: "Creation timestamp",
			},
			"docker_args": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Docker arguments",
				MarkdownDescription: "Docker arguments",
			},
			"env": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Environment variables as ['KEY=VALUE', ...] - DEPRECATED: Use container.env in v2",
				MarkdownDescription: "Environment variables as ['KEY=VALUE', ...] - DEPRECATED: Use container.env in v2 format (array of `key=value` strings).",
			},
			"gpu_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of GPUs (default: 1)",
				MarkdownDescription: "Number of GPUs (default: 1)",
				Default:             int64default.StaticInt64(1),
			},
			"gpu_type_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Specific GPU type ID (optional, will auto-select if not specified)",
				MarkdownDescription: "Specific GPU type ID (optional, will auto-select if not specified)",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Pod ID (assigned after creation)",
				MarkdownDescription: "Pod ID (assigned after creation)",
			},
			"image_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Docker image name (required if template_id is not specified)",
				MarkdownDescription: "Docker image name (required if template_id is not specified)",
			},
			"locked": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether pod is locked",
				MarkdownDescription: "Whether pod is locked",
			},
			"machine_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Machine ID to deploy pod on (optional if gpu_type_id is specified)",
				MarkdownDescription: "Machine ID to deploy pod on (optional if gpu_type_id is specified)",
			},
			"memory_in_gb": schema.Float64Attribute{
				Computed:            true,
				Description:         "Memory allocated in GB",
				MarkdownDescription: "Memory allocated in GB",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Pod name",
				MarkdownDescription: "Pod name",
			},
			"port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Main port for the pod - DEPRECATED: Use ports array instead",
				MarkdownDescription: "Main port for the pod - DEPRECATED: Use ports array instead (e.g., `ports = [\"8888/http\"]`).",
			},
			"ports": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Port configuration string",
				MarkdownDescription: "Port configuration string",
			},
			"start_jupyter": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Start Jupyter notebook on boot - DEPRECATED: Not supported in v2 API",
				MarkdownDescription: "Start Jupyter notebook on boot - DEPRECATED: Not supported in v2 API. Start Jupyter manually inside the pod or use a custom Docker image that starts Jupyter automatically.",
			},
			"start_ssh": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Start SSH on boot - DEPRECATED: Not supported in v2 API",
				MarkdownDescription: "Start SSH on boot - DEPRECATED: Not supported in v2 API. Start SSH manually inside the pod or use a custom Docker image that starts SSH automatically.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Current pod status",
				MarkdownDescription: "Current pod status",
			},
			"stop_after": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Auto-stop timestamp (ISO 8601) - DEPRECATED: Not supported in v2 API",
				MarkdownDescription: "Auto-stop timestamp (ISO 8601) - DEPRECATED: Not supported in v2 API. Use `runpod_pod_action` with action `stop` to stop pods manually.",
			},
			"template_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Pod template ID (optional, auto-select if not specified)",
				MarkdownDescription: "Pod template ID (optional, auto-select if not specified)",
			},
			"terminate_after": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Auto-terminate timestamp (ISO 8601) - DEPRECATED: Not supported in v2 API",
				MarkdownDescription: "Auto-terminate timestamp (ISO 8601) - DEPRECATED: Not supported in v2 API. Use `runpod_pod_action` with action `terminate` to terminate pods manually.",
			},
			"vcpu_count": schema.Float64Attribute{
				Computed:            true,
				Description:         "Virtual CPU count",
				MarkdownDescription: "Virtual CPU count",
			},
			"volume_in_gb": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Volume size in GB",
				MarkdownDescription: "Volume size in GB",
			},
			"volume_key": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "Volume encryption key - DEPRECATED: Not supported in v2 API",
				MarkdownDescription: "Volume encryption key - DEPRECATED: Not supported in v2 API. Use `volume_encrypted` for basic encryption support.",
			},
			"volume_mount_path": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Volume mount path",
				MarkdownDescription: "Volume mount path",
			},
			"network_volume_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Network volume ID to attach to the pod",
				MarkdownDescription: "Network volume ID to attach to the pod. When attached, the network volume replaces the pod volume.",
			},
			"docker_entrypoint": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Docker entrypoint array",
				MarkdownDescription: "Docker entrypoint array",
			},
			"docker_start_cmd": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Docker start command array",
				MarkdownDescription: "Docker start command array",
			},
			"interruptible": schema.BoolAttribute{
				Optional:            true,
				Description:         "Whether pod is interruptible - DEPRECATED: Use `type` field instead",
				MarkdownDescription: "Whether pod is interruptible - DEPRECATED: Use `type` field instead. Set `type = \"SPOT\"` for interruptible pods.",
			},
			"volume_encrypted": schema.BoolAttribute{
				Optional:            true,
				Description:         "Whether volume is encrypted",
				MarkdownDescription: "Whether volume is encrypted",
			},
		},
	}
}

type PodModel struct {
	Type              types.String  `tfsdk:"type"`  // v2 required field: ON_DEMAND or SPOT
	BidPerGpu         types.Float64 `tfsdk:"bid_per_gpu"`
	CloudType         types.String  `tfsdk:"cloud_type"`
	ClusterIp         types.String  `tfsdk:"cluster_ip"`
	ContainerDiskInGb types.Int64   `tfsdk:"container_disk_in_gb"`
	CostPerHr         types.Float64 `tfsdk:"cost_per_hr"`
	CreatedAt         types.String  `tfsdk:"created_at"`
	DockerArgs        types.String  `tfsdk:"docker_args"`
	Env               types.List    `tfsdk:"env"`
	GpuCount          types.Int64   `tfsdk:"gpu_count"`
	GpuTypeId         types.String  `tfsdk:"gpu_type_id"`
	Id                types.String  `tfsdk:"id"`
	ImageName         types.String  `tfsdk:"image_name"`
	Locked            types.Bool    `tfsdk:"locked"`
	MachineId         types.String  `tfsdk:"machine_id"`
	MemoryInGb        types.Float64 `tfsdk:"memory_in_gb"`
	Name              types.String  `tfsdk:"name"`
	Port              types.Int64   `tfsdk:"port"`
	Ports             types.String  `tfsdk:"ports"`
	StartJupyter      types.Bool    `tfsdk:"start_jupyter"`
	StartSsh          types.Bool    `tfsdk:"start_ssh"`
	Status            types.String  `tfsdk:"status"`
	StopAfter         types.String  `tfsdk:"stop_after"`
	TemplateId        types.String  `tfsdk:"template_id"`
	TerminateAfter    types.String  `tfsdk:"terminate_after"`
	VcpuCount         types.Float64 `tfsdk:"vcpu_count"`
	VolumeInGb        types.Float64 `tfsdk:"volume_in_gb"`
	VolumeKey         types.String  `tfsdk:"volume_key"`
	VolumeMountPath   types.String  `tfsdk:"volume_mount_path"`
  NetworkVolumeId   types.String  `tfsdk:"network_volume_id"`
  DockerEntrypoint  types.List    `tfsdk:"docker_entrypoint"`
  DockerStartCmd    types.List    `tfsdk:"docker_start_cmd"`
  Interruptible     types.Bool    `tfsdk:"interruptible"`
  VolumeEncrypted   types.Bool    `tfsdk:"volume_encrypted"`
}
