// Code generated by terraform-plugin-framework-generator DO NOT EDIT.
// MANUALLY EXTENDED: added per-data-center GPU availability (gpu_availability)
// plus the gpu_count / secure_cloud input arguments used to query it. See
// data_centers_data_source.go Read() for the matching GraphQL query/parsing.

package datasource_data_centers

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DataCentersDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"gpu_count": schema.Int64Attribute{
				Optional:            true,
				Description:         "GPU count used when querying per-data-center GPU availability (default 1)",
				MarkdownDescription: "GPU count used when querying per-data-center GPU availability (default 1).",
			},
			"secure_cloud": schema.BoolAttribute{
				Optional:            true,
				Description:         "Whether to query availability for SECURE cloud (default true)",
				MarkdownDescription: "Whether to query availability for SECURE cloud (default true).",
			},
			"data_centers": schema.ListNestedAttribute{
				Computed:            true,
				Description:         "List of data centers",
				MarkdownDescription: "List of data centers",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"global_network": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether global network is enabled",
							MarkdownDescription: "Whether global network is enabled",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "Data center ID",
							MarkdownDescription: "Data center ID",
						},
						"location": schema.StringAttribute{
							Computed:            true,
							Description:         "Data center location",
							MarkdownDescription: "Data center location",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Data center name",
							MarkdownDescription: "Data center name",
						},
						"gpu_availability": schema.ListNestedAttribute{
							Computed:            true,
							Description:         "Per-GPU-type availability for this data center",
							MarkdownDescription: "Per-GPU-type availability for this data center",
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"gpu_type_id": schema.StringAttribute{
										Computed:            true,
										Description:         "GPU type ID (e.g. 'NVIDIA H100 80GB HBM3')",
										MarkdownDescription: "GPU type ID (e.g. `NVIDIA H100 80GB HBM3`)",
									},
									"display_name": schema.StringAttribute{
										Computed:            true,
										Description:         "Human-friendly GPU name (e.g. 'H100 SXM')",
										MarkdownDescription: "Human-friendly GPU name (e.g. `H100 SXM`)",
									},
									"stock_status": schema.StringAttribute{
										Computed:            true,
										Description:         "Stock status: High/Medium/Low = in stock, None = out of stock",
										MarkdownDescription: "Stock status: `High`/`Medium`/`Low` = in stock, `None` = out of stock",
									},
									"available": schema.BoolAttribute{
										Computed:            true,
										Description:         "Whether the requested gpu_count is purchasable in this data center",
										MarkdownDescription: "Whether the requested `gpu_count` is purchasable in this data center",
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

type GpuAvailabilityModel struct {
	GpuTypeId   types.String `tfsdk:"gpu_type_id"`
	DisplayName types.String `tfsdk:"display_name"`
	StockStatus types.String `tfsdk:"stock_status"`
	Available   types.Bool   `tfsdk:"available"`
}

type DataCentersModel struct {
	GlobalNetwork   types.Bool             `tfsdk:"global_network"`
	Id              types.String           `tfsdk:"id"`
	Location        types.String           `tfsdk:"location"`
	Name            types.String           `tfsdk:"name"`
	GpuAvailability []GpuAvailabilityModel `tfsdk:"gpu_availability"`
}

type DataCentersDataSourceModel struct {
	GpuCount    types.Int64        `tfsdk:"gpu_count"`
	SecureCloud types.Bool         `tfsdk:"secure_cloud"`
	DataCenters []DataCentersModel `tfsdk:"data_centers"`
}
